### ISSUE TITLE
상품 데이터 입력

### ISSUE THREAD

**Issue by chhak0503** [khm9990503/Kmarket1#27]
- 관리자/상품등록 기능구현이 완료 후 상품데이터 입력하기
- 각 카테고리별 상품 데이터 입력하기
- 각 카테고리별 최소 10개 이상 입력하기(모든 팀원 1명당 3개이상 카테고리 담당)
- 상품 데이터와 이미지는 오픈마켓(Gmarket) 참고하기

**Comment by khm9990503** [comment]
- 상품 등록 사이트 : http://3.35.170.228:8080/Java1_Kmarket1/admin/product/register.do

- [ ]  홍모 : 컴퓨터 , 스포츠
- [ ]  중현 : 홈데코 , 여행
- [ ]  인화 : 브랜드패션, 패션의류*잡화
- [ ]  채영 : 유아동 , 식품, 자동차

- 팀원들은 상품 등록을 완료했으면 위에 체크해주세요.

**Comment by khm9990503** [comment]
- 상품등록 모두 완료, 아래 sql문 적용 완료
update `km_product` set `sold`=CEILING(RAND()*100);
update `km_product` set `hit`=CEILING(RAND()*100);
update `km_product` set `score`=CEILING(RAND()*5);
update `km_product` set `review`=CEILING(RAND()*100);
