### ISSUE TITLE
기능구현 - 관리자/상품등록(admin/product/register)

### ISSUE THREAD

**Issue by chhak0503** [khm9990503/Kmarket1#28]
- http://localhost:8080/Kmarket/admin/product/register.do
- 스토리보드 개발 가이드 참고

**Comment by SBUX1992** [comment]
2022-12-09 금
1. register관련 작업
- AdminProductRegisterController 작업 완료
- ProductDao insertProduct 추가
- SQL INSERT_PRODUCT 추가
- AdminProductRegister.js 상품명 중복 유효성검사 작성중

**Comment by khm9990503** [comment]
2022-12-11 일

- 상품 등록 기능 1차 구현 완료, 상품 등록이 가능합니다.
- 상품 등록 사이트 : http://3.35.170.228:8080/Java1_Kmarket1/admin/product/register.do
- 유효성 기능(2차)는 아직 미구현

**Comment by SBUX1992** [comment]
2022-12-13 화
1. register 상품등록 
 - 판매가격의 1%를 포인트로 자동계상 추가
 - a태그 추가하여 알림 문구 추가 (문구 및 색상 변경 필요하여 논의 요청)

**Comment by SBUX1992** [comment]
2022-12-14 수
할인율 표시
 - 할인가격 및 할인된 금액 표기

**Comment by SBUX1992** [comment]
2022-12-15 목

1. List 작업
- ListController doGet 작업중
- ListService 작업중
- ProductDao 작업중
- SQL 작업중
